### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by stubhbw** [zhiqiang-series/smart-show#48]
version : com.github.zhiqiang-series.smart-show:toast:3.1.6

java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.Toast.setView(android.view.View)' on a null object reference
  at y6.i(CompactToast.java:100)
        at g7.c(AbstractToastFactory.java:32)
        at e7.d(EmotionToastInvoker.java:247)
        at e7.c(EmotionToastInvoker.java:142)
        at s6.d(SmartToast.java:173)

**Comment by stubhbw** [comment]
项目混淆了，这是线上报的Bug，很难复现。沿着代码看是 CompactToast 里 weakReference<toast>.get().setView() 为空导致

**Comment by zhiqiang-series** [comment]
> 项目混淆了，这是线上报的Bug，很难复现。沿着代码看是 CompactToast 里 weakReference.get().setView() 为空导致

你好，该问题最新版本已修复过，尝试下最新版本，若仍有问题可及时反馈。
