### ISSUE TITLE
使用自定义SmartShow异常IllegalArgumentException

### ISSUE THREAD

**Issue by duning1204** [zhiqiang-series/smart-show#49]
> Fatal Exception: java.lang.IllegalArgumentException: View=DecorView@7b768cb[LoginActivity] not attached to window manager
       at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:550)
       at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:454)
       at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:141)
       at android.app.Dialog.dismissDialog(Dialog.java:420)
       at android.app.Dialog.dismiss(Dialog.java:402)
       at androidx.appcompat.app.AppCompatDialog.dismiss(NiuRenameJava:1)
       at com.coder.zzq.smartshow.toast.h.e.d(NiuRenameJava:2)
       at com.coder.zzq.smartshow.toast.h.a.run()

请尽快修复哈

**Comment by duning1204** [comment]
dismiss的时候try一下也行，麻烦更新下sdk

**Comment by zdxiang** [comment]
HONOR HNANY-Q (HONOR Magic4 Lite 5G android 13 也遇到这个问题，try我也加了，还是出现这个问题，请问如何解决？
